apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: mysql-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-pod

  template:
    metadata:
      name: mysql-pod
      labels:
        app: mysql-pod
    spec:
      containers:
      - image: mysql:5.7
        name: database
        envFrom:
          - secretRef:
              name: secret
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: bookstore-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: bookstore-storage
        persistentVolumeClaim:
          claimName: bookstore-pvc