apiVersion: v1
kind: PersistentVolume
metadata:
  name: bookstore-pv
  labels:
    type: local-mysql
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/ubuntu/deneme/kubernetes-yaml-files"