apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    app: result-service
spec:
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30002
  type: NodePort
  selector:
     app: result-pod