apiVersion: apps/v1
kind: Deployment
metadata:
  name:  web-deploy
  labels:
    app: web-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-pod
  template:
    metadata:
      labels:
        app: web-pod
    spec:
      containers:
      - name: web-container
        image: amazwhale/webserver:1.6
        envFrom:
          - secretRef:
              name: secret
        ports:
        - containerPort: 80
        resources:
            limits:
              memory: 500Mi
              cpu: 100m
            requests:
              memory: 250Mi
              cpu: 80m	